version: "3.8"

services:
  db:
    image: postgres:latest
    network_mode: "host"
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=bob
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  api:
    network_mode: "host"
    build:
      context: .
    ports:
      - 8002:8002
    volumes:
      - ./:/app
    links:
      - "db:database"
