FROM python:slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN python3 -m pip install tortoise-orm pytest asynctest requests

COPY . .
CMD ["python3","-m","pytest" , "-s" , "app/spec/test_ws_user_api.py"]